### ISSUE TITLE
New courses

### ISSUE THREAD

**Issue by HTenkanen** [GDSL-UL/Teaching_Links#2]
Hi @alexsingleton,

some course materials that weren't part of the list:
- https://geo-python.github.io
- https://autogis.github.io
- https://www.earthdatascience.org/

**Comment by davewhipp** [comment]
I was just going to make a pull request to add these (at least the first two) :D

**Comment by alexsingleton** [comment]
Feel free to do 

> I was just going to make a pull request to add these (at least the first two) :D

Feel free to do that I will add...

**Comment by davewhipp** [comment]
Pull request created, thanks!

**Comment by ljwolf** [comment]
Addressed in #4  :)
